(() => {
  const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches, menu=document.querySelector('#menu'), menuBtn=document.querySelector('.menu-btn');
  menuBtn.onclick=()=>{const open=menu.classList.toggle('open');menuBtn.setAttribute('aria-expanded',open);menuBtn.innerHTML=`<i class="ph ph-${open?'x':'list'}"></i>`};menu.querySelectorAll('a').forEach(a=>a.onclick=()=>menu.classList.remove('open'));
  const cart=new Map(), itemsEl=document.querySelector('#order-items'), empty=document.querySelector('#order-empty'), totalEl=document.querySelector('#order-total'), send=document.querySelector('#send-order');
  const money=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  function render(){itemsEl.innerHTML='';let total=0;cart.forEach((item,name)=>{total+=item.price*item.qty;const line=document.createElement('div');line.className='order-line';line.innerHTML=`<div><strong>${item.qty}x ${name}</strong><br><small>${money(item.price*item.qty)}</small></div><button type="button" aria-label="Remover uma unidade de ${name}"><i class="ph ph-minus"></i></button>`;line.querySelector('button').onclick=()=>{item.qty--;if(item.qty<1)cart.delete(name);render()};itemsEl.append(line)});empty.hidden=cart.size>0;totalEl.textContent=money(total);send.classList.toggle('disabled',cart.size===0)}
  document.querySelectorAll('[data-add]').forEach(btn=>btn.onclick=()=>{const name=btn.dataset.add,price=Number(btn.dataset.price),item=cart.get(name)||{price,qty:0};item.qty++;cart.set(name,item);render();document.querySelector('#monte').scrollIntoView({behavior:reduce?'auto':'smooth'})});
  document.querySelector('#clear-order').onclick=()=>{cart.clear();render()};send.onclick=()=>{if(!cart.size)return;const list=[...cart].map(([n,i])=>`${i.qty}x ${n}`).join('\n');const note=document.querySelector('#order-note').value.trim();const msg=`Olá! Montei uma prévia de pedido pelo site:\n${list}${note?`\nObservação: ${note}`:''}\n\nPode confirmar disponibilidade, guarnições e valor final?`;open(`https://wa.me/5585996736391?text=${encodeURIComponent(msg)}`,'_blank','noopener')};
  if(!window.gsap||reduce)return;gsap.registerPlugin(ScrollTrigger);gsap.timeline().from('.hero-copy>*',{opacity:0,y:45,stagger:.1,duration:.85,ease:'power3.out'}).from('.hero-photo',{scale:1.12,duration:1.5,ease:'power3.out'},0);gsap.to('.hero-photo',{scale:1.08,yPercent:5,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1}});gsap.to('.menu-image',{rotate:-2,xPercent:-8,ease:'none',scrollTrigger:{trigger:'.menu-intro',start:'top bottom',end:'bottom top',scrub:1}});gsap.from('.repeat-tile',{y:110,rotate:5,scale:.9,opacity:.35,ease:'none',scrollTrigger:{trigger:'.repeat-story',start:'top 85%',end:'center 52%',scrub:1}});gsap.to('.repeat-stamp',{rotate:369,ease:'none',scrollTrigger:{trigger:'.repeat-story',start:'top bottom',end:'bottom top',scrub:1}});if(innerWidth>820){const track=document.querySelector('.menu-track'),section=document.querySelector('.menu-pan');gsap.to(track,{x:()=>-(track.scrollWidth-innerWidth),ease:'none',scrollTrigger:{trigger:section,start:'top top',end:()=>`+=${track.scrollWidth-innerWidth}`,pin:true,scrub:1,invalidateOnRefresh:true}})}gsap.utils.toArray('.reveal').forEach(el=>gsap.from(el,{y:70,opacity:0,duration:1,scrollTrigger:{trigger:el,start:'top 82%'}}));gsap.to('.sun i',{rotate:180,ease:'none',scrollTrigger:{trigger:'.visit',start:'top bottom',end:'bottom top',scrub:1}});ScrollTrigger.create({start:30,onUpdate:s=>document.querySelector('#nav').classList.toggle('scrolled',s.scroll()>30)});addEventListener('load',()=>ScrollTrigger.refresh(),{once:true});
})();
