(() => {
  const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;const menuBtn=document.querySelector('.menu-btn');const menu=document.querySelector('#menu');
  menuBtn?.addEventListener('click',()=>{const open=menu.classList.toggle('open');menuBtn.setAttribute('aria-expanded',String(open));menuBtn.innerHTML=`<i class="ph ph-${open?'x':'list'}"></i>`});menu?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>menu.classList.remove('open')));
  let vibe='',material='';const result=document.querySelector('#style-result');const contact=document.querySelector('#style-contact');const labels={
    'leve-metal':['Metal fino','Uma referência discreta, com linhas leves e acabamento essencial.'],'leve-translucida':['Transparência suave','Tons claros e volume delicado para um visual leve.'],'leve-acetato':['Acetato limpo','Uma armação de espessura moderada e desenho simples.'],
    'criativa-metal':['Metal gráfico','Aros com desenho incomum e leveza visual.'],'criativa-translucida':['Cor transparente','Um ponto de cor sem esconder a expressão.'],'criativa-acetato':['Forma autoral','Geometria e cor como parte do seu estilo.'],
    'marcante-metal':['Metal amplo','Traço fino em proporção maior para criar presença.'],'marcante-translucida':['Volume translúcido','Contraste de tamanho com luz atravessando a armação.'],'marcante-acetato':['Geometria forte','Linhas definidas e acetato com mais presença.']};
  function update(){if(!vibe||!material)return;const item=labels[`${vibe}-${material}`];result.innerHTML=`<span>Sua referência</span><strong>${item[0]}</strong><p>${item[1]}</p>`;contact.classList.remove('disabled');contact.href=`https://www.instagram.com/pro.otica/`;}
  document.querySelectorAll('[data-vibe]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-vibe]').forEach(item=>item.classList.remove('selected'));button.classList.add('selected');vibe=button.dataset.vibe;update()}));
  document.querySelectorAll('[data-material]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-material]').forEach(item=>item.classList.remove('selected'));button.classList.add('selected');material=button.dataset.material;update()}));
  if(!window.gsap||reduce)return;gsap.registerPlugin(ScrollTrigger);
  gsap.timeline().from('.hero-copy > *',{y:44,opacity:0,duration:.9,stagger:.1,ease:'power3.out'}).from('.hero-photo',{scale:1.1,duration:1.45,ease:'power3.out'},0);
  gsap.to('.hero-photo',{scale:1.08,yPercent:6,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1}});gsap.to('.hero-lens',{rotate:145,xPercent:12,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1.2}});
  const gallery=document.querySelector('.frame-gallery');if(innerWidth>760){gsap.to(gallery,{x:()=>-(gallery.scrollWidth-innerWidth+80),ease:'none',scrollTrigger:{trigger:'.collection',start:'top top',end:()=>`+=${gallery.scrollWidth-innerWidth+500}`,pin:true,scrub:1,invalidateOnRefresh:true}})}
  gsap.to('.finder-portrait img',{yPercent:-11,ease:'none',scrollTrigger:{trigger:'.finder',start:'top bottom',end:'bottom top',scrub:1}});gsap.to('.lens-window',{scale:1.18,rotate:8,ease:'none',scrollTrigger:{trigger:'.finder',start:'top 85%',end:'bottom 20%',scrub:1}});
  gsap.utils.toArray('.journey-stack article').forEach((card,index)=>{if(index===2)return;gsap.to(card,{scale:.92,opacity:.55,ease:'none',scrollTrigger:{trigger:document.querySelectorAll('.journey-stack article')[index+1],start:'top bottom',end:'top top',scrub:true}})});
  gsap.utils.toArray('.reveal').forEach(el=>gsap.from(el,{y:62,opacity:0,duration:1,scrollTrigger:{trigger:el,start:'top 84%'}}));gsap.to('.optic-orbit',{rotateY:180,rotateZ:50,ease:'none',scrollTrigger:{trigger:'.location',start:'top bottom',end:'bottom top',scrub:1}});
  ScrollTrigger.create({start:40,onUpdate:self=>document.querySelector('#nav').classList.toggle('scrolled',self.scroll()>40)});addEventListener('load',()=>ScrollTrigger.refresh(),{once:true});
})();
